version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: urlpass
      POSTGRES_DB: urldb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urluser -d urldb"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.15.2
    command: [
      "-path", "/migrations",
      "-database", "postgres://urluser:urlpass@db:5432/urldb?sslmode=disable",
      "up"
    ]
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=:8080
      - DATABASE_URL=postgres://urluser:urlpass@db:5432/urldb?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  db_data: